from enum import Enum

class SensitivityLevel (str, Enum):
    NULL = "NULL"
    SENSITIVE_US_CITIZENS = "SENSITIVE - US CITIZENS"
    SENSITIVE_US_PERSONS = "SENSITIVE - US PERSONS"
    SENSITIVE_UK_CITIZENS = "SENSITIVE - UK CITIZENS"
    SENSITIVE_UK_PERSONS = "SENSITIVE - UK PERSONS"
    UNRESTRICTED = "UNRESTRICTED"